server:
    port: 8080

spring :
    jackson :
        date-format : yyyy-MM-dd
        time-zone : GMT+8
        serialization :
            write-dates-as-timestamps : false
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/tvseries?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456

mybatis.configuration.mapUnderscoreToCamelCase: true

logging :
    file : target/app.log
    level :
        charset: UTF-8 
        root : WARN
        spider.television.controller: TRACE
        

    
